version: '3.8'

services:
  omnius:
    build: .
    container_name: omnius-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    networks:
      - omnius-network

networks:
  omnius-network:
    driver: bridge 