version: '3.8'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "3"
    compress: "true"

services:
  omnius:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PIP_PROGRESS_BAR=on
        - PIP_TIMEOUT=300
        - BUILDKIT_INLINE_CACHE=1
    container_name: omnius-bot
    restart: unless-stopped
    init: true
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
      - ./config:/app/config:ro
      - ./models:/app/models:ro
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      - ENABLE_ML=true
    # Health check to verify the bot is running
    healthcheck:
      test: ["CMD", "python3", "-c", "print('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    logging: *default-logging
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:size=200M,noexec

networks:
  default:
    name: omnius-network 